# Generated by Django 5.2 on 2025-05-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_homeslider_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Upload icon image', upload_to='features/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Page Feature',
                'verbose_name_plural': 'Home Page Features',
            },
        ),
    ]
