# Generated by Django 5.2 on 2025-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_homefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeature',
            name='svg_icon_id',
            field=models.CharField(blank=True, help_text="Use the ID of an SVG icon in your sprite, e.g., 'quality'. Leave blank to use uploaded image.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
    ]
