# Generated by Django 5.2 on 2025-05-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
