# Generated by Django 5.2 on 2025-05-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='catslug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
