# Generated by Django 5.2 on 2025-05-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_productcategory_catslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='catslug',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
