# Generated by Django 5.2 on 2025-05-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
