# Generated by Django 5.2 on 2025-05-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20250514_0950'),
        ('dashboard', '0023_blog'),
    ]

    operations = [
    ]
